/**
 * Permission matrix — role → allowed permission strings
 * Used by auth store's hasPermission() action.
 */
import type { UserRole } from '~/types/database'

export const PERMISSION_MATRIX: Record<UserRole, string[]> = {
  super_admin: ['*'],
  admin: [
    'shop.view_dashboard',
    'shop.edit_settings',
    'shop.manage_paymongo',
    'shop.manage_payment_methods',
    'shop.verify_payments',
    'shop.view_bookings',
    'shop.create_booking',
    'shop.cancel_booking',
    'staff.add',
    'staff.edit',
    'staff.delete',
    'staff.assign_roles',
    'cms.services',
    'cms.gallery',
    'cms.products',
    'cms.inventory',
    'loyalty.configure',
    'loyalty.view_points',
    'loyalty.adjust_points',
    'loyalty.redeem_points',
    'reports.view_logs',
    'reports.view_financial',
    'reports.export',
  ],
  manager: [
    'shop.view_dashboard',
    'shop.edit_settings',
    'shop.manage_payment_methods',
    'shop.verify_payments',
    'shop.view_bookings',
    'shop.create_booking',
    'shop.cancel_booking',
    'staff.add',
    'staff.edit',
    'cms.services',
    'cms.gallery',
    'cms.products',
    'cms.inventory',
    'loyalty.view_points',
    'loyalty.adjust_points',
    'loyalty.redeem_points',
    'reports.view_logs',
    'reports.view_financial',
    'reports.export',
  ],
  cashier: [
    'shop.view_dashboard',
    'shop.verify_payments',
    'shop.view_bookings',
    'shop.create_booking',
    'shop.cancel_booking',
    'cms.products',
    'cms.inventory',
    'loyalty.view_points',
    'loyalty.redeem_points',
    'reports.view_financial',
  ],
  barber: [
    'shop.view_dashboard',
    'shop.view_bookings',
    'shop.create_booking',
    'barber.set_availability',
    'barber.view_own_bookings',
    'barber.update_booking_status',
  ],
  customer: [
    'customer.book',
    'customer.view_bookings',
    'customer.cancel_booking',
    'customer.view_loyalty',
    'customer.redeem_rewards',
  ],
}
